### ISSUE TITLE
Feature request: Add folder/directory renaming, name scheme

### ISSUE THREAD

**Issue by jthrow0451** [stashapp/CommunityScripts#25]
I may eventually look into this, putting this here to track progress.

Should be able to organize media around the base library folder and create directories based on a predefined name scheme.

E.g., /BaseFolder/Studio/Year/Scene-with-formatted-fields.mp4

We could have a template like:
$studio/$year/$title

Where "/" would denote a folder directory scheme relative to the base library folder.

One thing to consider would be any external files that are associated to media, potentially transferring them too (e.g., a folder.jpg alongside a single scene)

**Comment by jeremymeyers** [comment]
I feel pretty strongly that Stash should not be a file management system. It introduces a whole other layer of potential break points and is really outside the scope of the project. There are plenty of file management solutions to help people get organized.

Anyway kind of the whole point of the project is an abstraction layer on top of however you have your files organized.

I would rather see this work go into something like the ability to toggle  particular scanned folders on and off for visibility within the interface, so for example if i had a folder of kink stuff that i didn't want to be displayed all the time, but wanted to have in the database and be able to navigate through it when i so choose, I can.

**Comment by Jerrk** [comment]
This is something i am interested in as well and i have a suggestion to add.

i like organizing my media by performer as in /basefolder/$performer/$year/$title.ext

but since some titles contain multiple performers i would suggest that stash could create hardlinks inbetween the performer directories

although the hardlink part might be out of the scope for this issue and be something i bring up separately in the future.

**Comment by NozomiClambie** [comment]
I feel like this feature makes perfect sense for Stash! Especially once you toggle the "Organized" flag to true. 

To be honest, when I first stumbled onto stash, I thought the tagline of "Stash is a self-hosted webapp written in Go which organizes and serves your porn." meant I could do exactly this. That's literally all I needed to read to get me to dive in lol

I still love stash even after finding out this functionality didn't exist and it's something I can get by without but some kind of folder organization would definitely make the hoarder in me ecstatic!

**Comment by MRobi1** [comment]
> There are plenty of file management solutions to help people get organized.

The issue with using other file management solutions to get organized as far as file naming/folder structure goes is that it all must be done prior to using stash. Otherwise any file/folder renamed will need to be cleared from the database and then scanned back in. But then any identifying or tagging that was done on the file will be lost. Plus, sometimes you'll want the folder structure to be based on the tags added by stash. It's a very inefficient approach.

This sounds like a great feature request for renamerOnUpdate or SQlite_Renamer since they update the stash database with the new path at the same time.

**Comment by jeremymeyers** [comment]
> > There are plenty of file management solutions to help people get organized.
> 
> The issue with using other file management solutions to get organized as far as file naming/folder structure goes is that it all must be done prior to using stash. Otherwise any file/folder renamed will need to be cleared from the database and then scanned back in. But then any identifying or tagging that was done on the file will be lost. Plus, sometimes you'll want the folder structure to be based on the tags added by stash. It's a very inefficient approach.
> 
> This sounds like a great feature request for renamerOnUpdate or SQlite_Renamer since they update the stash database with the new path at the same time.

This is not true.  If you generate phashes, rescanning the directories will correctly identify the files in their new locations and update the database accordingly.

**Comment by MRobi1** [comment]
> This is not true. If you generate phashes, rescanning the directories will correctly identify the files in their new locations and update the database accordingly.

Is this anywhere in the documentation or just one of those things you have to know? I read through the in-app manual as well as the faq on github and see no record of this anywhere. 

Googling it I can see part of an explanation "Stash will recognize the files on the next scan and re-link to the new location. Do not run a Clean in between these steps, or you will lose the information ..." but clicking the link brings to the FAQ where there rest of that sentence is gone.

I personally have perceptual hashes on as part of my generate task and just 2 days ago renamed about 1,000 files in bulk. I'm still working through re-tagging them all. So if there's a way I can automate the rest I'd love to know how.

**Comment by jeremymeyers** [comment]
I guess it's something i know. Will check with the discord as to whether there is documentation.  For the moment, you should be able to rescan the directories and it should re-match the data.

**Comment by jeremymeyers** [comment]
https://github.com/stashapp/stash/wiki/FAQ#how-do-i-rename-or-relocate-a-library-folder

**Comment by NozomiClambie** [comment]
I was aware of the relocating files capability and being able to do so without losing data (providing you don't start a clean task during the process) prior to my initial comment supporting this request. And that has been handy with post-processing after scraping with stash (Currently I use a very crude script to place files into folders based onto their title + run kodi helper to generate nfo's after filenames have been formatted nicely using renamerOnUpdate).

For me that info is one of those things where you stumble upon the it once and it sort of just sticks but can never remember where you read it or learned it from lol I'm not even sure I read it on that github wiki FAQ, might have been on discord maybe but good to know it's actually in the wiki!

With that said, I still agree folder organization should be a feature of either stash itself or would be a great functionality addition to renamerOnUpdate/SQlite_Renamer. As strongly as @jeremymeyers feels against this request is probably how strongly I feel in favor of this request!

I obviously can't speak for how everyone handles their data or if I'm in the majority or minority here
But rather than pre-organizing everything prior to adding to stash, I'm in the group of people that would likely scrape data for their files with stash, then use that scraped data to organize their files as it seems more logical (or, at least, makes things significantly easier to organize files based on scraped data after the fact but that's merely my opinion) to do it that way. Especially with how handy stashbox matching is!

If I were more knowledgeable in python, I would have already adapted either renamerOnUpdate or SQlite_Renamer to support this already! But alas, I'm still very new to python and have only really tackled some community scrapers so far!

**Comment by scruffynerf** [comment]
RenamerOnUpdate is the tool the community has gotten behind. Replacing the much older Renamer or SqliteRenamer...

We'll be revamping that for v24, and there are tons of open issues on it to review and close.  This is one of them!

Used correctly, RenamerOnUpdate will make subfolders.  It cannot make folders outside of your library any longer.  This is by design.
