### ISSUE TITLE
[renamerOnUpdate] configuration reset after update

### ISSUE THREAD

**Issue by dirtcase** [stashapp/CommunityScripts#263]
Based on the documentation we should make our configuration changes to `config.py` but according to the code this file is only loaded when the `renamerOnUpdate_config.py` file cannot be imported. Shouldn't this be the other way round?

I made changes to `renamerOnUpdate_config.py` but these were undone after updating the plugin.

**Comment by stg-annon** [comment]
indeed the config file would ideally be untracked by GIT/Manifest so that when updated customizations to the config are not lost

the way the plugin is written currently you should be able to rename `renamerOnUpdate_config.py` to `config.py` to solve this but it will otherwise import `renamerOnUpdate_config.py` if it exists

PR #264 fixes this
