### ISSUE TITLE
stashUserscriptLibrary replacement

### ISSUE THREAD

**Issue by feederbox826** [stashapp/CommunityScripts#315]
While SUL has been very helpful in developing plugins, the majority of functions are not used, have been deprecated by PluginAPI or have been improved in personal forks and repositories. 

This is a tracking issue for rewriting SUL to be more narrowly scoped and replace functions with built-in APIs

**Comment by DogmaDragon** [comment]
List of plugins that use it:
- [ ] [StashBatchResultToggle](https://github.com/stashapp/CommunityScripts/tree/main/plugins/StashBatchResultToggle) - should probably be removed completely, since it's covered by https://github.com/7dJx1qP/stash-plugins/tree/main/plugins/stashBatchResultToggle.
- [ ] [VideoScrollWheel](https://github.com/stashapp/CommunityScripts/tree/main/plugins/VideoScrollWheel)
- [ ] [discordPresence](https://github.com/stashapp/CommunityScripts/tree/main/plugins/discordPresence)
- [ ] [sceneCoverCropper](https://github.com/stashapp/CommunityScripts/tree/main/plugins/sceneCoverCropper)
- [ ] [stashAI](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stashAI)
- [ ] [stashRealbooru](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stashRealbooru)
- [ ] [stats](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stats)
- [ ] [themeSwitch](https://github.com/stashapp/CommunityScripts/tree/main/plugins/themeSwitch)
- [ ] [visage](https://github.com/stashapp/CommunityScripts/tree/main/plugins/visage)

**Comment by feederbox826** [comment]
Replicating so I can edit it

List of plugins that use it:
* [ ]  [StashBatchResultToggle](https://github.com/stashapp/CommunityScripts/tree/main/plugins/StashBatchResultToggle) - should probably be removed completely, since it's covered by https://github.com/7dJx1qP/stash-plugins/tree/main/plugins/stashBatchResultToggle.
* [x]  [VideoScrollWheel](https://github.com/stashapp/CommunityScripts/tree/main/plugins/VideoScrollWheel)
* [ ]  [discordPresence](https://github.com/stashapp/CommunityScripts/tree/main/plugins/discordPresence)
* [ ]  [sceneCoverCropper](https://github.com/stashapp/CommunityScripts/tree/main/plugins/sceneCoverCropper)
* [ ]  [stashAI](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stashAI)
* [ ]  [stashRealbooru](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stashRealbooru)
* [x]  [stats](https://github.com/stashapp/CommunityScripts/tree/main/plugins/stats)
* [ ]  [themeSwitch](https://github.com/stashapp/CommunityScripts/tree/main/plugins/themeSwitch)
* [ ]  [visage](https://github.com/stashapp/CommunityScripts/tree/main/plugins/visage)

**Comment by feederbox826** [comment]
All done. The name is kinda shitty but it's all done
